# ☕ Coffee Shop Sales & Spatial Analytics

## 1. Business Understanding

### 1.1 Business Problem

### 1.2 Business Objectives

### 1.3 Business Questions

## Data Understanding

### 2.1 Import Library

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

### 2.2 Load Dataset

In [2]:
df = pd.read_csv("coffee_shop_sales.csv")
df.head()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,1/1/2023,7:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,1/1/2023,7:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,1/1/2023,7:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,1/1/2023,7:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,1/1/2023,7:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg

### 2.3 Dataset Overview

In [3]:
df.tail()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
149111,149452,6/30/2023,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg
149112,149453,6/30/2023,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg
149113,149454,6/30/2023,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg
149114,149455,6/30/2023,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino
149115,149456,6/30/2023,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup

In [4]:
df.sample(5)

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
80158,80332,4/30/2023,17:14:35,2,8,Hell's Kitchen,31,2.20,Coffee,Gourmet brewed coffee,Ethiopia Sm
105009,105263,5/23/2023,12:35:22,2,8,Hell's Kitchen,30,3.00,Coffee,Gourmet brewed coffee,Columbian Medium Roast Lg
70411,70581,4/19/2023,8:31:19,1,3,Astoria,46,2.50,Tea,Brewed Green tea,Serenity Green Tea Rg
89499,89753,5/9/2023,14:42:24,1,3,Astoria,5,15.00,Coffee beans,Gourmet Beans,Columbian Medium Roast
7118,7148,1/13/2023,15:06:50,1,3,Astoria,40,3.75,Coffee,Barista Espresso,Cappuccino

In [5]:
df.shape

(149116, 11)

### 2.4 Data Structure

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   transaction_date  149116 non-null  object
 2   transaction_time  149116 non-null  object
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  object
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  object
 9   product_type      149116 non-null  object
 10  product_detail    149116 non-null  object
dtypes: float64(1), int64(4), object(6)
memory usage: 12.5+ MB

In [7]:
df.columns

Index(['transaction_id', 'transaction_date', 'transaction_time',
       'transaction_qty', 'store_id', 'store_location', 'product_id',
       'unit_price', 'product_category', 'product_type', 'product_detail'],
      dtype='object')

In [8]:
df.dtypes

transaction_id        int64
transaction_date     object
transaction_time     object
transaction_qty       int64
store_id              int64
store_location       object
product_id            int64
unit_price          float64
product_category     object
product_type         object
product_detail       object
dtype: object

### 2.5 Sumarry Statistic

In [9]:
df.describe(include="all")

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
count,149116.000000,149116,149116,149116.000000,149116.000000,149116,149116.000000,149116.000000,149116,149116,149116
unique,NaN,181,25762,NaN,NaN,3,NaN,NaN,9,29,80
top,NaN,6/19/2023,9:31:15,NaN,NaN,Hell's Kitchen,NaN,NaN,Coffee,Brewed Chai tea,Chocolate Croissant
freq,NaN,1343,41,NaN,NaN,50735,NaN,NaN,58416,17183,3076
mean,74737.371872,NaN,NaN,1.438276,5.342063,NaN,47.918607,3.382219,NaN,NaN,NaN
std,43153.600016,NaN,NaN,0.542509,2.074241,NaN,17.930020,2.658723,NaN,NaN,NaN
min,1.000000,NaN,NaN,1.000000,3.000000,NaN,1.000000,0.800000,NaN,NaN,NaN
25%,37335.750000,NaN,NaN,1.000000,3.000000,NaN,33.000000,2.500000,NaN,NaN,NaN
50%,74727.500000,NaN,NaN,1.000000,5.000000,NaN,47.000000,3.000000,NaN,NaN,NaN
75%,112094.250000,NaN,NaN,2.000000,8.000000,NaN,60.000000,3.750000,NaN,NaN,NaN
max,149456.000000,NaN,NaN,8.000000,8.000000,NaN,87.000000,45.000000,NaN,NaN,NaN

## 3 DATA PREPARATION

### 3.1 Missing Value

In [10]:
df.isnull().sum()

transaction_id      0
transaction_date    0
transaction_time    0
transaction_qty     0
store_id            0
store_location      0
product_id          0
unit_price          0
product_category    0
product_type        0
product_detail      0
dtype: int64

### 3.2 Duplicate Data

In [11]:
df.duplicated().sum()

np.int64(0)

### 3.3 Data Type Validation

In [12]:
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

### 3.4 Feature Engineering

In [13]:
df['Revenue'] = df['transaction_qty'] * df['unit_price']

In [14]:
df['Month'] = df['transaction_date'].dt.month_name()

In [15]:
df['Day'] = df['transaction_date'].dt.day_name()

In [16]:
df['Hour'] = df['transaction_date'].dt.hour

## 4. Exploratory Data Analysis

### 4.1 Sales Performance

In [22]:
# Total Revenue
df['Revenue'].sum()

np.float64(698812.3300000002)

In [20]:
# Total Transaction
df['transaction_id'].nunique()

149116

In [21]:
# Total Quantity
df['transaction_qty'].sum()

np.int64(214470)

### 4.2 Product Performance

In [18]:
df.groupby('product_detail')['Revenue'].sum().sort_values(ascending=False)

product_detail
Sustainably Grown Organic Lg    21151.75
Dark chocolate Lg               21006.00
Latte Rg                        19112.25
Cappuccino Lg                   17641.75
Morning Sunrise Chai Lg         17384.00
                                  ...
Lemon Grass                      1360.40
Guatemalan Sustainably Grown     1340.00
Spicy Eye Opener Chai            1335.90
Earl Grey                        1270.90
Dark chocolate                    755.20
Name: Revenue, Length: 80, dtype: float64

### 4.3 Store Performance

In [19]:
df.groupby('store_location')['Revenue'].sum()

store_location
Astoria            232243.91
Hell's Kitchen     236511.17
Lower Manhattan    230057.25
Name: Revenue, dtype: float64

### 4.4 Time Analysis

#### revenue month analysis

In [24]:
monthly_revenue = (
    df.groupby('Month')['Revenue']
      .sum()
      .reset_index()
)

monthly_revenue

      Month    Revenue
0     April  118941.08
1  February   76145.19
2   January   81677.74
3      June  166485.88
4     March   98834.68
5       May  156727.76

In [25]:
month_order = [
    'January','February','March','April','May','June',
    'July','August','September','October','November','December'
]

monthly_revenue['Month'] = pd.Categorical(
    monthly_revenue['Month'],
    categories=month_order,
    ordered=True
)

monthly_revenue = monthly_revenue.sort_values('Month')

#### revenue day analysis

In [26]:
daily_revenue = (
    df.groupby('Day')['Revenue']
      .sum()
      .reset_index()
)

daily_revenue

         Day    Revenue
0     Friday  101373.00
1     Monday  101677.28
2   Saturday   96894.48
3     Sunday   98330.31
4   Thursday  100767.78
5    Tuesday   99455.94
6  Wednesday  100313.54

In [27]:
day_order = [
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Sunday'
]

daily_revenue['Day'] = pd.Categorical(
    daily_revenue['Day'],
    categories=day_order,
    ordered=True
)

daily_revenue = daily_revenue.sort_values('Day')

#### peak hour

In [30]:
hourly_sales = (
    df.groupby('Hour')['Revenue']
      .sum()
      .reset_index()
)

hourly_sales

   Hour    Revenue
0     0  698812.33

##### jam tersibuk

In [31]:
hourly_sales.sort_values(
    by='Revenue',
    ascending=False
).head()

   Hour    Revenue
0     0  698812.33

### 4.5 spatial analysis

In [32]:
store_location = pd.DataFrame({
    'store_location':[
        "Hell's Kitchen",
        "Astoria",
        "Lower Manhattan"
    ],
    'Latitude':[
        40.764,
        40.764,
        40.707
    ],
    'Longitude':[
        -73.991,
        -73.923,
        -74.011
    ]
})

In [33]:
df = df.merge(
    store_location,
    on='store_location',
    how='left'
)

In [34]:
store_revenue = (
    df.groupby(
        ['store_location','Latitude','Longitude']
    )['Revenue']
    .sum()
    .reset_index()
)

store_revenue

    store_location  Latitude  Longitude    Revenue
0          Astoria    40.764    -73.923  232243.91
1   Hell's Kitchen    40.764    -73.991  236511.17
2  Lower Manhattan    40.707    -74.011  230057.25

In [35]:
fig = px.scatter_mapbox(
    store_revenue,
    lat='Latitude',
    lon='Longitude',
    size='Revenue',
    color='Revenue',
    hover_name='store_location',
    zoom=10,
    mapbox_style='open-street-map',
    title='Revenue by Store Location'
)

fig.show()

C:\Users\sabil\AppData\Local\Temp\ipykernel_28072\3073583732.py:1: DeprecationWarning: *scatter_mapbox* is deprecated! Use *scatter_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/
  fig = px.scatter_mapbox(

In [36]:
df.columns

Index(['transaction_id', 'transaction_date', 'transaction_time',
       'transaction_qty', 'store_id', 'store_location', 'product_id',
       'unit_price', 'product_category', 'product_type', 'product_detail',
       'Revenue', 'Month', 'Day', 'Hour', 'Latitude', 'Longitude'],
      dtype='object')